# Generated by Django 3.2 on 2022-04-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmodel',
            table='employees',
        ),
    ]
