# Generated by Django 3.2 on 2022-04-14 10:17

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_empmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=1000)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'FeaturedListing',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='listing_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_of_property', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.property')),
            ],
            options={
                'verbose_name_plural': 'PropertyImages',
            },
        ),
    ]
