# Generated by Django 3.2 on 2022-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220414_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
