# Generated by Django 3.2 on 2022-06-12 16:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220526_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'ourteam',
            },
        ),
    ]
