# Generated by Django 3.2 on 2022-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_ourteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteam',
            old_name='position',
            new_name='positions',
        ),
    ]
