# Generated by Django 4.0.2 on 2022-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_property_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='describe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
