# Generated by Django 4.0.2 on 2022-07-20 11:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_property_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_of_property', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.featuredlisting')),
            ],
            options={
                'verbose_name_plural': 'FeaturedImages',
            },
        ),
    ]
