# Generated by Django 4.0.2 on 2022-07-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_featuredlisting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredlisting',
            name='description',
        ),
    ]
