# Generated by Django 4.0.2 on 2022-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_featuredlisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
