# Generated by Django 4.0.2 on 2022-08-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_visitors_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='visitors',
        ),
    ]
