# Generated by Django 3.2 on 2022-02-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
