# Generated by Django 3.2 on 2022-04-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
