# Generated by Django 3.2 on 2022-04-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_property_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
