# Generated by Django 3.2 on 2022-02-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220214_1358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='Property',
        ),
    ]
