# Generated by Django 3.2 on 2022-02-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_property_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Property'},
        ),
    ]
