# Generated by Django 3.2 on 2022-02-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='accomodation',
        ),
    ]
